#' qaqc_stic_data
#'
#' @description This function provides multiple options for QAQC flagging of processed and classified STIC data frames, such as those generated by the \link{classify_wetdry} function.
#' Users can select which operations are to be performed, and a character flag is added as an addition column in the input data frame.
#' Users also have to option to concatenate multiple flags into one column. QAQC options currently include...
#'
#' @param stic_data A data frame with classified STIC data, such as that produced by \code{classify_wetdry}.
#' @param spc_neg_correction a logical argument indicating whether the user would like to correct negative SPC values resulting from the calibration process to 0.
#' The character code associated with this correction is \code{"N"}.
#' @param inspect_classification a logical argument indicating whether the user would like to identify instances in which either a wet or dry reading is surrounded on both sides by 1000 or more observations of its opposite.
#' This operation is meant to identify potentially suspect binary wet/dry data points for further examination.
#' The character code associated with this operation is \code{"A"}.
#' @param anomaly_size a numeric argument specifying the maximum size (i.e., number of observations) of a clustered group of points that can be flagged as an anomaly
#' @param window_size a numeric argument specifying the minimum size (i.e., number of observations) that the anomaly must be surrounded by in order to be flagged
#' @param concatenate_flags a logical argument indicating whether the user would like to combine the character codes generated into a single QAQC flag column.
#' @import dplyr
#' @import data.table
#'
#' @return The same data frame as input, but with new QAQC columns or a single, concatenated QAQC column
#' @export
#'
#' @examples qaqc_df <- qaqc_stic_data(classified_df, spc_neg_correction = TRUE, inspect_classification = TRUE, anomaly_size = 4, window_size = 1000, concatenate_flags = TRUE)

qaqc_stic_data <- function(stic_data, spc_neg_correction = TRUE, inspect_classification = TRUE,
                           anomaly_size = 4, window_size = 1000, concatenate_flags = TRUE) {

  if (spc_neg_correction == TRUE) {

    # Deal with negative spc values
    stic_data <- stic_data |>
      dplyr::mutate(SpC = dplyr::if_else(
        condition = SpC <= -1,
        true = 0,
        false = SpC)) |>
      dplyr::mutate(negative_SpC = dplyr::if_else(
        condition = SpC == 0,
        true = "N",
        false = "" ))
  }

  if (inspect_classification == TRUE) {


    # Get run lengths from rle object
    rle_object <- rle(stic_data$wetdry)
    run_lengths <- rle_object$lengths

    # This is working
    stic_data <- dplyr::group_by(stic_data, data.table::rleid(wetdry)) |>
      dplyr::mutate(n = n()) |>
      dplyr::ungroup() |>
      dplyr::mutate(anomaly_tf = wetdry != lag(wetdry, 1, default = "")
                    & wetdry != lead(wetdry, 1, default = "")
                    & lag(n, 1, default = 0) > 1000 & lead(n, 1, default = 0) > 1000)


    i_small <- which(run_lengths < anomaly_size)

    for (i in i_small){
      i_window <- run_lengths[i_small-1] + run_lengths[i_small+1]

      if (i_window > window_size) {
        anomaly_start <- sum(run_lengths[1:(i-1)])+1
        anomaly_end <- anomaly_start + run_lengths[i]-1
      }
    }

    stic_data$anomaly <- rep("", nrow(stic_data))
    df[anomaly_start:anomaly_end, "anomaly"] <- "A"

    stic_data <- stic_data |>
      dplyr::select(-c(data.table::rleid(wetdry), anomaly_tf, n))
  }

  if (concatenate_flags == TRUE) {

    # concatenate the QAQC columns with col codes: "N" for negative SpC;
    # "A" for anomalous classification; "O" for outside standard range
    stic_data$QAQC <-
      stringr::str_c(stic_data$negative_SpC, '', stic_data$anomaly, '', stic_data$outside_range)

    stic_data <- stic_data |>
      select(-c(negative_SpC, anomaly, outside_range))

  }

  return(stic_data)

}


