#' qaqc_stic_data
#'
#' @description This function provides multiple options for QAQC flagging of processed and classified STIC data frames, such as those generated by the `classify_wetdry function`.
#' Users can select which operations are to be performed, and a character flag is added as an addition column in the input data frame.
#' Users also have to option to concatenate multiple flags into one column. QAQC options currently include...
#'
#' @param stic_data A data frame with classified STIC data, such as that produced by `classify_wetdry`
#' @param spc_neg_correction a logical argument indicating whether the user would like to correct negative SPC values resulting from the calibration process to 0.
#' The character code associated with this correction is "A".
#' @param inspect_classification a logical argument indicating whether the user would like to identify instances in which either a wet or dry reading is surrounded on both sides by 1000 or more observations of its opposite.
#' This operation is meant to identify potentially suspect binary wet/dry data points for further examination.
#' The character code associated with this operation is "B".
#' @param concatenate_flags a logical argument indicating whether the user would like to combine the character codes generated into a single QAQC flag column.
#'
#' @return The same data frame as input, but with new QAQC columns or a single, concatenated QAQC column
#' @export
#'
#' @examples

qaqc_stic_data <- function(stic_data, spc_neg_correction = TRUE, inspect_classification = TRUE,
                           concatenate_flags = TRUE) {

  if (spc_neg_correction == TRUE) {

    # Deal with negative spc values (maybe move to previous script)
    stic_data <- stic_data %>%
      mutate(SpC = if_else(
        condition = SpC <= -1,
        true = 0,
        false = SpC)) %>%
      mutate(negative_SpC = if_else(
        condition = SpC == 0,
        true = "A",
        false = "" ))
  }

  if (inspect_classification == TRUE) {

    # This is working
    stic_data <- group_by(stic_data, data.table::rleid(wetdry)) %>%
      mutate(n = n()) %>%
      ungroup() %>%
      mutate(anomaly_tf = classification != lag(classification, 1, default = "")
             & classification != lead(classification, 1, default = "")
             & lag(n, 1, default = 0) > 1000 & lead(n, 1, default = 0) > 1000)

    stic_data$anomaly <- dplyr::if_else(stic_data$anomaly_tf == TRUE, "B", "" )

    stic_data <- stic_data %>%
      select(-c(data.table::rleid(wetdry), anomaly_tf, n))

  }

 if (concatenate_flags == TRUE) {

   # concatenate the QAQC columns with col codes: "A" for negative SpC;
   # "B" for anomalous classification
   stic_data$QAQC <-
     stringr::str_c(stic_data$negative_SpC, '', stic_data$anomaly)

   stic_data <- stic_data %>%
     select(-c(negative_SpC, anomaly))

 }

  return(stic_data)

}


