#' test_threshold.R
#'
#' @description This function is intended to allow the user to visually assess the effects of classification threshold uncertainty on STIC classification. It takes the the model object used to calibrate SpC, as well as a classified STIC data frame with column names matching those produced by `classify_wetdry`
#'
#' @param stic_data classified STIC data frame with the variable names of that produced by `classify_wetdry`
#' @param SpC_calibration_model the model object used to calibrate SpC, generated by the `get_calibration` function and used in `apply_calibration`
#'
#' @return A time series plot of classified wet/dry observations through time using three different absolute classification thresholds: the y-intercept of the fitted model developed in get_calibration, the y-intercept plus one standard error, and the y-intercept minus one standard error
#' @export
#'
#' @examples lm_calibration <- get_calibration(calibration_standard_data, method = "linear")
#' threshold_testing_plot <- test_threshold(stic_data = classified_df, SpC_calibration_model = lm_calibration)
#'

test_threshold <- function(stic_data, SpC_calibration_model) {

  # Extracting y-intercept
  y_int <- SpC_calibration_model$coefficients[2]

  # Extracting and using standard error
  model_summary <- summary(SpC_calibration_model)
  se <- model_summary$sigma

  y_int_plus_se <- y_int + se
  y_int_minus_se <- y_int - se

  # Now can make a df for plotting by classifying according the the three absolute thresholds
  threshold_df <- classified_df %>%
    mutate(wetdry_yint = dplyr::if_else(SpC >= y_int, "wet", "dry")) %>%
    mutate(wetdry_yint_plus_se = dplyr::if_else(SpC >= y_int_plus_se, "wet", "dry")) %>%
    mutate(wetdry_yint_minus_se = dplyr::if_else(SpC >= y_int_minus_se, "wet", "dry"))

  # Reshaping this for categorical plotting
  threshold_long <- threshold_df %>%
    pivot_longer(cols = c(wetdry_yint, wetdry_yint_plus_se, wetdry_yint_minus_se),
                 names_to = "Threshold", values_to = "classification")

  # Making a time series line graph of wet network proportion colored by the three methods
  wet_network_prop <- threshold_long %>%
    group_by(datetime, Threshold) %>%
    summarise(n_wet = sum(classification == "wet"), n_sensors = n() ) %>%
    mutate(percent = n_wet/n_sensors)

  time_series_plot <- ggplot(wet_network_prop, aes(x = datetime, y = percent, color = Threshold)) +
    geom_line()

  return(time_series_plot)

}



